name: CI/CD Pipeline - Titanic MLOps

on:
  push:
    branches:
      - master

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar dependências e rodar testes
        run: |
          pip install -r src/requirements.txt
          pip install pytest
          PYTHONPATH=src pytest tests/test_api.py

      - name: Configurar Credenciais AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Aplicar Infra (Terraform)
        working-directory: ./infra
        run: |
          terraform init
          terraform apply -auto-approve